In [1]:
from __future__ import print_function
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from keras.preprocessing import sequence
from sklearn.preprocessing import label_binarize
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Convolution1D,MaxPooling1D, Flatten
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU ,Bidirectional, CuDNNLSTM ,BatchNormalization ,Flatten, Attention
from keras.datasets import imdb
from keras.utils.np_utils import to_categorical
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn import metrics
from sklearn.preprocessing import Normalizer , LabelEncoder , StandardScaler
import h5py
from keras import callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from matplotlib import pyplot as plt
from sklearn.metrics import matthews_corrcoef
import math
from sklearn.metrics import roc_curve, auc, roc_auc_score
from keras.layers import LSTM, Dense, Bidirectional, Input,Dropout,BatchNormalization, CuDNNGRU, CuDNNLSTM
from itertools import cycle

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv(r'/content/drive/MyDrive/MSCAD/MSCAD.csv', header=0)

In [ ]:
c=[ 3,  7, 12, 13, 15, 16, 22, 23, 24, 25, 33, 34, 36, 39, 50, 52, 56, 57]
data=data[c]]

In [ ]:
data[data.columns[66]]

0         Brute_Force
1         Brute_Force
2         Brute_Force
3         Brute_Force
4         Brute_Force
             ...     
128794         Normal
128795         Normal
128796         Normal
128797         Normal
128798         Normal
Name: Label, Length: 128799, dtype: object

In [ ]:
data['Label'].value_counts()

Brute_Force    88502
Normal         28502
Port_Scan      11081
HTTP_DDoS        641
ICMP_Flood        45
Web_Crwling       28
Name: Label, dtype: int64

In [ ]:
data.dtypes

'Flow Duration'       int64
'Tot Fwd Pkts'        int64
'Tot Bwd Pkts'        int64
'TotLen Fwd Pkts'     int64
'TotLen Bwd Pkts'     int64
                      ...  
'Idle Mean'           int64
'Idle Std'            int64
'Idle Max'            int64
'Idle Min'            int64
Label                object
Length: 67, dtype: object

In [ ]:
traindata, testdata = train_test_split(df,test_size=0.20,random_state=42)

In [ ]:
traindata, testdata = train_test_split(data,test_size=0.20)

In [ ]:
label=LabelEncoder()
data[data.columns[66]]=label.fit_transform(data[data.columns[66]])

In [ ]:
data

In [ ]:
traindata['Label'].value_counts()

0    70856
3    22722
4     8894
1      507
2       40
5       20
Name: Label, dtype: int64

In [ ]:
testdata['Label'].value_counts()

0    17646
3     5780
4     2187
1      134
5        8
2        5
Name: Label, dtype: int64

In [ ]:
testdata[66].value_counts()

In [ ]:
X = data.iloc[:,0:66]
Y = data.iloc[:,66]

In [ ]:
X

'Flow Duration'  'Tot Fwd Pkts'  'Tot Bwd Pkts'  'TotLen Fwd Pkts'  \
0                  1518               2               5                110   
1                  5894               4               8                168   
2                   272               1               1                  0   
3                  2611               4               8                322   
4                   294               1               1                  0   
...                 ...             ...             ...                ...   
128794            68942               3               2                517   
128795            63327               2               2               1277   
128796           139061               3               3                517   
128797         21641848               2               5                  0   
128798           248023               0               2                  0   

        'TotLen Bwd Pkts'  'Fwd Pkt Len Max'  'Fwd Pkt Len Min'  \
0                     377                110                  0   
1                    4498                168                  0   
2                       0                  0                  0   
3                    4434                322                  0   
4                       0                  0                  0   
...                   ...                ...                ...   
128794                  0                517                  0   
128795               1356               1277                  0   
128796                  0                517                  0   
128797                  1                  0                  0   
128798                  0                  0                  0   

        'Fwd Pkt Len Mean'  'Fwd Pkt Len Std'  'Bwd Pkt Len Max'  ...  \
0                  55.0000            77.7817                377  ...   
1                  42.0000            84.0000               1460  ...   
2                   0.0000             0.0000                  0  ...   
3                  80.5000           161.0000               1460  ...   
4                   0.0000             0.0000                  0  ...   
...                    ...                ...                ...  ...   
128794            172.3333           298.4901                  0  ...   
128795            638.5000           902.9754               1356  ...   
128796            172.3333           298.4901                  0  ...   
128797              0.0000             0.0000                  1  ...   
128798              0.0000             0.0000                  0  ...   

        'Init Bwd Win Byts'  'Fwd Act Data Pkts'  'Active Mean'  'Active Std'  \
0                        46                    1              0             0   
1                        54                    1              0             0   
2                      4106                    0              0             0   
3                        54                    1              0             0   
4                      4106                    0              0             0   
...                     ...                  ...            ...           ...   
128794                65535                    1              0             0   
128795                    0                    1              0             0   
128796                  261                    1              0             0   
128797                  257                    0        3242118             0   
128798                 1026                    0              0             0   

        'Active Max'  'Active Min'  'Idle Mean'  'Idle Std'  'Idle Max'  \
0                  0             0            0           0           0   
1                  0             0            0           0           0   
2                  0             0            0           0           0   
3                  0             0            0           0           0   
4                  0             0       

In [ ]:
Y

0         0
1         0
2         0
3         0
4         0
         ..
128794    3
128795    3
128796    3
128797    3
128798    3
Name: Label, Length: 128799, dtype: int64

In [ ]:
scaler = StandardScaler().fit(X)
trainX = scaler.transform(X)
# summarize transformed data
np.set_printoptions(precision=3)



In [ ]:
label=LabelEncoder()
Y=label.fit_transform(data[data.columns[66]])


In [ ]:
df=pd.DataFrame(trainX)

In [ ]:
df[66]=Y

In [ ]:
df[66].value_counts()

0    88502
3    28502
4    11081
1      641
2       45
5       28
Name: 66, dtype: int64

In [ ]:
y_train=traindata['Label'].values
y_test=testdata['Label'].values

In [ ]:
trainX=traindata.iloc[:,0:66].values
testX=testdata.iloc[:,0:66].values

#y_train=to_categorical(traindata['Label'])
#y_test=to_categorical(testdata['Label'])

In [ ]:
# initializing all the model objects with default parameters
#Classifier

et=ExtraTreesClassifier()
xgb=xgb.XGBClassifier()
rf=RandomForestClassifier()
dt=DecisionTreeClassifier()
svm=SVC()
knn=KNeighborsClassifier()
ada=AdaBoostClassifier()
nvb=GaussianNB()

In [ ]:
def algo(classifier):

  #check each classifier accuracy here
  clf=classifier
  clf.fit(trainX,y_train)
  y_pred=clf.predict(testX)
  acc=accuracy_score(y_test,y_pred)
  prc=precision_score(y_test,y_pred, average="weighted")
  rc=recall_score(y_test,y_pred, average="weighted")
  f1=f1_score(y_test,y_pred, average="weighted")
  print(classifier)
  print('Accuracy: ',acc, '\nPrecision: ' ,prc, '\nRecall: ', rc,'\nF1-Score: ', f1)
  print(acc)
  print(classification_report(y_test,y_pred))
  print(metrics.confusion_matrix(y_test, y_pred))

In [ ]:
algo(dt)

DecisionTreeClassifier()
Accuracy:  0.9978649068322981 
Precision:  0.9978884220242165 
Recall:  0.9978649068322981 
F1-Score:  0.9978679959463959
0.9978649068322981
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17713
           1       0.96      0.97      0.96       137
           2       0.44      0.67      0.53         6
           3       1.00      0.99      1.00      5641
           4       0.99      1.00      0.99      2256
           5       0.40      0.29      0.33         7

    accuracy                           1.00     25760
   macro avg       0.80      0.82      0.80     25760
weighted avg       1.00      1.00      1.00     25760

[[17708     0     0     5     0     0]
 [    0   133     0     1     3     0]
 [    0     0     4     2     0     0]
 [    3     4     3  5612    16     3]
 [    0     2     1     7  2246     0]
 [    0     0     1     3     1     2]]


In [ ]:
algo(rf)

RandomForestClassifier()
Accuracy:  0.9982531055900621 
Precision:  0.9982698790571041 
Recall:  0.9982531055900621 
F1-Score:  0.9982060444387029
0.9982531055900621
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17713
           1       0.98      0.98      0.98       137
           2       0.57      0.67      0.62         6
           3       1.00      1.00      1.00      5641
           4       1.00      0.99      0.99      2256
           5       1.00      0.29      0.44         7

    accuracy                           1.00     25760
   macro avg       0.92      0.82      0.84     25760
weighted avg       1.00      1.00      1.00     25760

[[17705     0     0     5     3     0]
 [    0   134     0     1     2     0]
 [    0     1     4     1     0     0]
 [    2     0     2  5633     4     0]
 [    8     2     0     9  2237     0]
 [    0     0     1     4     0     2]]


In [ ]:
algo(knn)

KNeighborsClassifier()
Accuracy:  0.9968167701863354 
Precision:  0.9965947290158811 
Recall:  0.9968167701863354 
F1-Score:  0.9967001572445068
0.9968167701863354
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17713
           1       0.94      0.98      0.96       137
           2       0.50      0.67      0.57         6
           3       1.00      0.99      0.99      5641
           4       0.99      0.99      0.99      2256
           5       0.00      0.00      0.00         7

    accuracy                           1.00     25760
   macro avg       0.74      0.77      0.75     25760
weighted avg       1.00      1.00      1.00     25760

[[17706     0     0     6     1     0]
 [    0   134     0     1     2     0]
 [    0     1     4     1     0     0]
 [    9     1     3  5609    19     0]
 [   10     7     0    14  2225     0]
 [    1     0     1     5     0     0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: 

In [ ]:
algo(nvb)

GaussianNB()
Accuracy:  0.7689052795031056 
Precision:  0.8226095256633268 
Recall:  0.7689052795031056 
F1-Score:  0.7553218170393785
0.7689052795031056
              precision    recall  f1-score   support

           0       0.87      1.00      0.93     17713
           1       0.06      0.70      0.11       137
           2       0.00      0.67      0.01         6
           3       0.99      0.35      0.52      5641
           4       0.08      0.01      0.01      2256
           5       0.00      0.14      0.00         7

    accuracy                           0.77     25760
   macro avg       0.33      0.48      0.26     25760
weighted avg       0.82      0.77      0.76     25760

[[17701     4     0     1     0     7]
 [   41    96     0     0     0     0]
 [    0     1     4     1     0     0]
 [  553  1369   816  1993   132   778]
 [ 2034   151    31    23    12     5]
 [    0     5     1     0     0     1]]


In [ ]:
algo(svm)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVC()
Accuracy:  0.861723602484472 
Precision:  0.8718882261055393 
Recall:  0.861723602484472 
F1-Score:  0.8206808105336771
0.861723602484472


NameError: ignored

In [ ]:
import keras.backend as K
from keras.layers import Layer
from keras.layers import Input

In [ ]:
# Add attention layer to the deep learning network
class attention(Layer):
    def __init__(self,**kwargs):
        super(attention,self).__init__(**kwargs)
 
    def build(self,input_shape):
        self.W=self.add_weight(name='attention_weight', shape=(input_shape[-1],1), 
                               initializer='random_normal', trainable=True)
        self.b=self.add_weight(name='attention_bias', shape=(input_shape[1],1), 
                               initializer='zeros', trainable=True)        
        super(attention, self).build(input_shape)
 
    def call(self,x):
        # Alignment scores. Pass them through tanh function
        e = K.tanh(K.dot(x,self.W)+self.b)
        # Remove dimension of size 1
        e = K.squeeze(e, axis=-1)   
        # Compute the weights
        alpha = K.softmax(e)
        # Reshape to tensorFlow format
        alpha = K.expand_dims(alpha, axis=-1)
        # Compute the context vector
        context = x * alpha
        context = K.sum(context, axis=1)
        return context

In [ ]:
y_train

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)

In [ ]:
# reshape input to be [samples, time steps, features]
X_train = np.reshape(trainX, (trainX.shape[0], trainX.shape[1],1))
X_test=np.reshape(testX, (testX.shape[0], testX.shape[1],1))

print(X_train.shape)


batch_size = 32

(103039, 66, 1)


In [ ]:
model = Sequential()
model.add(LSTM(64,return_sequences=True, input_shape=(66,1)))
model.add(attention())
model.add(Dense(32,activation='relu'))
model.add(Dense(6, activation="softmax"))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_16 (LSTM)              (None, 66, 64)            16896     
                                                                 
 attention_13 (attention)    (None, 64)                130       
                                                                 
 dense_22 (Dense)            (None, 32)                2080      
                                                                 
 dense_23 (Dense)            (None, 6)                 198       
                                                                 
Total params: 19,304
Trainable params: 19,304
Non-trainable params: 0
_________________________________________________________________


In [ ]:
checkpointer = callbacks.ModelCheckpoint(filepath="kddresults/nslkddmc/checkpoint-{epoch:02d}.hdf5", verbose=1, save_best_only=True, monitor='val_accuracy',mode='max')
csv_logger = CSVLogger('training_set_iranalysis.csv',separator=',', append=False)
m1=model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test,y_test), callbacks=[checkpointer,csv_logger])

Epoch 1/50
3220/3220 [==============================] - ETA: 0s - loss: 0.3645 - accuracy: 0.8876
Epoch 1: val_accuracy improved from -inf to 0.95124, saving model to kddresults/nslkddmc/checkpoint-01.hdf5
3220/3220 [==============================] - 125s 38ms/step - loss: 0.3645 - accuracy: 0.8876 - val_loss: 0.1977 - val_accuracy: 0.9512
Epoch 2/50
3219/3220 [============================>.] - ETA: 0s - loss: 0.1878 - accuracy: 0.9522
Epoch 2: val_accuracy improved from 0.95124 to 0.96215, saving model to kddresults/nslkddmc/checkpoint-02.hdf5
3220/3220 [==============================] - 122s 38ms/step - loss: 0.1878 - accuracy: 0.9522 - val_loss: 0.1398 - val_accuracy: 0.9622
Epoch 3/50
3219/3220 [============================>.] - ETA: 0s - loss: 0.1412 - accuracy: 0.9645
Epoch 3: val_accuracy did not improve from 0.96215
3220/3220 [==============================] - 122s 38ms/step - loss: 0.1413 - accuracy: 0.9645 - val_loss: 0.1891 - val_accuracy: 0.9562
Epoch 4/50
3219/3220 [======

In [ ]:
checkpointer = callbacks.ModelCheckpoint(filepath="kddresults/nslkddmc/checkpoint-{epoch:02d}.hdf5", verbose=1, save_best_only=True, monitor='val_accuracy',mode='max')
csv_logger = CSVLogger('training_set_iranalysis.csv',separator=',', append=False)
m1=model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test,y_test), callbacks=[checkpointer,csv_logger])

In [ ]:

loss, accuracy = model.evaluate(X_test, y_test)
print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))
#y_pred = model.predict_classes(X_test)


805/805 [==============================] - 9s 11ms/step - loss: 0.0163 - accuracy: 0.9969

Loss: 0.02, Accuracy: 99.69%


In [ ]:
y_pred=model.predict(X_test) 
classes_x=np.argmax(y_pred,axis=1)
class_x=np.argmax(y_pred.round(),axis=1)

In [ ]:
y_true=np.argmax(y_test,axis=1)

In [ ]:
recall = recall_score(y_true, classes_x , average="weighted")
precision = precision_score(y_true, classes_x , average="weighted")
f1= f1_score(y_true, classes_x , average="weighted")

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_true,class_x))

NameError: ignored

In [ ]:

print("confusion matrix")
print("----------------------------------------------")
print("accuracy")
print("%.6f" %accuracy)
print("recall")
print("%.6f" %recall)
print("precision")
print("%.6f" %precision)
print("f1score")
print("%.6f" %f1)
cm = metrics.confusion_matrix(y_true, classes_x)
print("==============================================")
print (cm)

confusion matrix
----------------------------------------------
accuracy
0.996933
recall
0.996933
precision
0.996756
f1score
0.996825
[[17854     1     0     5     0     0]
 [    0   113     0     4     1     0]
 [    0     0     7     3     0     0]
 [   10     0     0  5587     5     0]
 [   24     9     0    12  2120     0]
 [    0     0     0     5     0     0]]


In [3]:
cm=[[17854     ,1     ,0     ,5     ,0     ,0],
 [    0  , 113    , 0     ,4    , 1    , 0],
 [    0    , 0     ,7     ,3    , 0   ,  0],
 [   10    , 0     ,0  ,5587    , 5   ,  0],
 [   24    , 9   ,  0   , 12 , 2120    , 0],
 [    0    , 0    , 0    , 5   ,  0    , 0]]


In [4]:
cm

[[17854, 1, 0, 5, 0, 0],
 [0, 113, 0, 4, 1, 0],
 [0, 0, 7, 3, 0, 0],
 [10, 0, 0, 5587, 5, 0],
 [24, 9, 0, 12, 2120, 0],
 [0, 0, 0, 5, 0, 0]]

In [10]:
cm.dtypes

AttributeError: ignored

In [11]:
cm=np.array(cm)

In [12]:
cm

array([[17854,     1,     0,     5,     0,     0],
       [    0,   113,     0,     4,     1,     0],
       [    0,     0,     7,     3,     0,     0],
       [   10,     0,     0,  5587,     5,     0],
       [   24,     9,     0,    12,  2120,     0],
       [    0,     0,     0,     5,     0,     0]])